name: extinct
description: "App for Gemini AI Competition"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  google_generative_ai: ^0.4.3
  google_maps_flutter: ^2.7.0
  photo_view: ^0.15.0
  page_transition: ^2.1.0
  in_app_review: ^2.0.9
  provider: ^6.1.2
  modal_bottom_sheet: ^3.0.0

  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/slider/
    - assets/slider/dodo/
    - assets/slider/thylacine/
    - assets/slider/quagga/
    - assets/slider/pigeon/
    - assets/slider/tortoise/
    - assets/slider/bucardo/
    - assets/avatar/
    - assets/resources/dodo/
    - assets/resources/thylacine/
    - assets/resources/quagga/
    - assets/resources/pigeon/
    - assets/resources/tortoise/
    - assets/resources/bucardo/


icons_launcher:
  image_path: "assets/ic_logo_border.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: '#000000'
      adaptive_foreground_image: "assets/ic_foreground.png"